spring:
  application:
    name: sharetreats_chatbot
  jpa:
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, prometheus, loggers
  metrics:
    tags:
      application: ${spring.application.name}