spring:
  config:
    activate:
      on-profile: dev
  application:
    name: sharetreats_chatbot
  jpa:
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    baseline-version: 1
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}