spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharetreats
    username: dlwlgh9412
    password: dlwlgh9412
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true