spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharetreats
    username: dlwlgh9412
    password: dlwlgh9412
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    baseline-version: 1
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  config: classpath:log4j2.xml
